"""Script data models for the reddit2shorts application.

This module defines data structures for video scripts and script segments
generated by LLM services.
"""

from dataclasses import dataclass
from typing import Dict, Any, List, Optional


@dataclass
class ScriptSegment:
    """Represents a single segment of a video script with timing information.
    
    A script segment is a portion of the video script that will be displayed
    as a subtitle or spoken at a specific time in the video.
    
    Attributes:
        text: The text content of this segment
        start_time: Start time in seconds from the beginning of the video
        end_time: End time in seconds from the beginning of the video
        duration: Duration of this segment in seconds
    """
    
    text: str
    start_time: float
    end_time: float
    duration: float
    
    def __post_init__(self):
        """Validate segment timing after initialization."""
        if self.start_time < 0:
            raise ValueError("start_time must be non-negative")
        if self.end_time < 0:
            raise ValueError("end_time must be non-negative")
        if self.duration < 0:
            raise ValueError("duration must be non-negative")
        if self.end_time < self.start_time:
            raise ValueError("end_time must be greater than or equal to start_time")
        if not self.text.strip():
            raise ValueError("text cannot be empty or whitespace-only")
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert the segment to a dictionary for serialization.
        
        Returns:
            Dictionary representation of the segment
            
        Examples:
            >>> segment = ScriptSegment(
            ...     text="Hello world",
            ...     start_time=0.0,
            ...     end_time=3.0,
            ...     duration=3.0
            ... )
            >>> segment.to_dict()
            {'text': 'Hello world', 'start_time': 0.0, 'end_time': 3.0, 'duration': 3.0}
        """
        return {
            'text': self.text,
            'start_time': self.start_time,
            'end_time': self.end_time,
            'duration': self.duration
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ScriptSegment':
        """Create a ScriptSegment from a dictionary.
        
        Args:
            data: Dictionary containing segment data
        
        Returns:
            ScriptSegment instance
            
        Examples:
            >>> data = {
            ...     'text': 'Hello world',
            ...     'start_time': 0.0,
            ...     'end_time': 3.0,
            ...     'duration': 3.0
            ... }
            >>> segment = ScriptSegment.from_dict(data)
            >>> segment.text
            'Hello world'
        """
        return cls(
            text=data['text'],
            start_time=data['start_time'],
            end_time=data['end_time'],
            duration=data['duration']
        )


@dataclass
class GeneratedScript:
    """Represents a complete video script generated by an LLM service.
    
    A generated script contains the full text of the script along with
    individual segments that have timing information for subtitles and
    text-to-speech synthesis.
    
    Attributes:
        full_text: The complete script text as a single string
        segments: List of script segments with timing information
        metadata: Additional metadata about the script generation
                 (e.g., model used, generation parameters)
    """
    
    full_text: str
    segments: List[ScriptSegment]
    metadata: Dict[str, Any]
    
    def __post_init__(self):
        """Validate script after initialization."""
        if not self.full_text.strip():
            raise ValueError("full_text cannot be empty or whitespace-only")
        if not self.segments:
            raise ValueError("segments list cannot be empty")
        
        # Validate segment timing consistency
        for i, segment in enumerate(self.segments):
            if i > 0:
                prev_segment = self.segments[i - 1]
                if segment.start_time < prev_segment.end_time:
                    raise ValueError(
                        f"Segment {i} start_time ({segment.start_time}) "
                        f"overlaps with previous segment end_time ({prev_segment.end_time})"
                    )
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert the script to a dictionary for serialization.
        
        Returns:
            Dictionary representation of the script
            
        Examples:
            >>> segment = ScriptSegment(
            ...     text="Hello world",
            ...     start_time=0.0,
            ...     end_time=3.0,
            ...     duration=3.0
            ... )
            >>> script = GeneratedScript(
            ...     full_text="Hello world",
            ...     segments=[segment],
            ...     metadata={'model': 'gpt-4'}
            ... )
            >>> result = script.to_dict()
            >>> result['full_text']
            'Hello world'
            >>> len(result['segments'])
            1
        """
        return {
            'full_text': self.full_text,
            'segments': [segment.to_dict() for segment in self.segments],
            'metadata': self.metadata
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'GeneratedScript':
        """Create a GeneratedScript from a dictionary.
        
        Args:
            data: Dictionary containing script data
        
        Returns:
            GeneratedScript instance
            
        Examples:
            >>> data = {
            ...     'full_text': 'Hello world',
            ...     'segments': [{
            ...         'text': 'Hello world',
            ...         'start_time': 0.0,
            ...         'end_time': 3.0,
            ...         'duration': 3.0
            ...     }],
            ...     'metadata': {'model': 'gpt-4'}
            ... }
            >>> script = GeneratedScript.from_dict(data)
            >>> script.full_text
            'Hello world'
        """
        segments = [ScriptSegment.from_dict(seg) for seg in data['segments']]
        
        return cls(
            full_text=data['full_text'],
            segments=segments,
            metadata=data.get('metadata', {})
        )
    
    def get_total_duration(self) -> float:
        """Calculate the total duration of the script.
        
        Returns:
            Total duration in seconds
            
        Examples:
            >>> segment1 = ScriptSegment("Hello", 0.0, 2.0, 2.0)
            >>> segment2 = ScriptSegment("World", 2.0, 5.0, 3.0)
            >>> script = GeneratedScript(
            ...     full_text="Hello World",
            ...     segments=[segment1, segment2],
            ...     metadata={}
            ... )
            >>> script.get_total_duration()
            5.0
        """
        if not self.segments:
            return 0.0
        return self.segments[-1].end_time
    
    def get_segment_count(self) -> int:
        """Get the number of segments in the script.
        
        Returns:
            Number of segments
            
        Examples:
            >>> segment = ScriptSegment("Hello", 0.0, 2.0, 2.0)
            >>> script = GeneratedScript(
            ...     full_text="Hello",
            ...     segments=[segment],
            ...     metadata={}
            ... )
            >>> script.get_segment_count()
            1
        """
        return len(self.segments)
